---
# https://github.com/alphagov/tech-docs-gem/blob/main/example/config/tech-docs.yml

host: https://ministryofjustice.github.io/hmpps-electronic-monitoring-create-an-order
show_govuk_logo: false
service_name: HMPPS Electronic Monitoring Create An Order
service_link: /
header_links:
enable_search: true
collapsible_nav: true
multipage_nav: true
max_toc_heading_level: 
prevent_indexing: true
show_contribution_banner: true
github_repo: ministryofjustice/hmpps-electronic-monitoring-create-an-order
github_branch: main
full_service_name: HMPPS Electronic Monitoring Create An Order
show_expiry: true
show_review_banner: true
